# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nok
user_description: Interested in working with data science effectively. Attracted by Numba, Dask recently, love to work with Jupyter Notebook. Learning how to do Test Drive Data Science.
user_title: Associate Data Scientist
email: channoklam@yahoo.com.hk
twitter_username: mediumnok
github_username:  noklam


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']


gems:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji