# Site settings
title: A blog about lorem ipsum dolor sit amet
description: Learn to be a better coder, and do data science effectively.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://abc.com

# User settings
username: Nok
user_description: Build neural nets with for cool problems, scikit-learn for not so cool problem and pandas for my actual work.
user_title: Associate Data Scientist
email: channoklam@yahoo.com.hk
twitter_username: mediumnok
github_username:  noklam


# Google-analytics
google-analytics:
  id: "UA-83544344-2"

exclude: ['package.json', 'src' , 'node_modules']


gems:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji